#=================================================================
# 对象存储配置，配置在nacos
#=================================================================
#storage:
#  type: minio # 对象存储类型
#  minio:
#    endpoint: http://127.0.0.1:9000
#    accessKey: xxxxxxx
#    secretKey: xxxxxxx
#  aliyun-oss:
#    # OSS 服务的访问域名，请根据实际使用的 OSS 区域替换为对应的 endpoint
#    endpoint: oss-cn-beijing.aliyuncs.com # 改成你自己的
#    # 阿里云账号的 AccessKey ID，用于身份验证
#    accessKey: xxxxxxx # 改成你自己的
#    # 阿里云账号的 AccessKey Secret，用于身份验证
#    secretKey: xxxxxxx # 改成你自己的

